#!/usr/bin/env sh

if nmcli c show --active | grep -q wireguard; then
  echo '{"text": "VPN", "class": "up"}'
elif nmcli c show --active | grep -q "YapiBiche"; then
  echo '{"text": "LAN", "class": "up"}'
elif nmcli c show --active | grep -q "Redmi"; then
  echo '{"text": "Phone", "class": "up"}'
else
  echo '{"text": "OFF", "class": "down"}'
fi
